# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/admin/Documents/airports.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.latminspl = QtWidgets.QSplitter(self.centralwidget)
        self.latminspl.setGeometry(QtCore.QRect(50, 90, 125, 37))
        self.latminspl.setOrientation(QtCore.Qt.Vertical)
        self.latminspl.setObjectName("latminspl")
        self.latmin = QtWidgets.QLabel(self.latminspl)
        self.latmin.setObjectName("latmin")
        self.latminline = QtWidgets.QLineEdit(self.latminspl)
        self.latminline.setObjectName("latminline")
        self.lonmaxspl = QtWidgets.QSplitter(self.centralwidget)
        self.lonmaxspl.setGeometry(QtCore.QRect(50, 140, 125, 37))
        self.lonmaxspl.setOrientation(QtCore.Qt.Vertical)
        self.lonmaxspl.setObjectName("lonmaxspl")
        self.lonmax = QtWidgets.QLabel(self.lonmaxspl)
        self.lonmax.setObjectName("lonmax")
        self.lonmaxline = QtWidgets.QLineEdit(self.lonmaxspl)
        self.lonmaxline.setObjectName("lonmaxline")
        self.lonminspl = QtWidgets.QSplitter(self.centralwidget)
        self.lonminspl.setGeometry(QtCore.QRect(50, 190, 125, 37))
        self.lonminspl.setOrientation(QtCore.Qt.Vertical)
        self.lonminspl.setObjectName("lonminspl")
        self.lonmin = QtWidgets.QLabel(self.lonminspl)
        self.lonmin.setObjectName("lonmin")
        self.lonminline = QtWidgets.QLineEdit(self.lonminspl)
        self.lonminline.setObjectName("lonminline")
        self.btsearch = QtWidgets.QPushButton(self.centralwidget)
        self.btsearch.setGeometry(QtCore.QRect(50, 250, 113, 32))
        self.btsearch.setObjectName("btsearch")
        self.btclear = QtWidgets.QPushButton(self.centralwidget)
        self.btclear.setGeometry(QtCore.QRect(50, 290, 113, 32))
        self.btclear.setObjectName("btclear")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(195, 1, 601, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.latmaxspl = QtWidgets.QSplitter(self.centralwidget)
        self.latmaxspl.setGeometry(QtCore.QRect(50, 40, 125, 37))
        self.latmaxspl.setOrientation(QtCore.Qt.Vertical)
        self.latmaxspl.setObjectName("latmaxspl")
        self.latmax = QtWidgets.QLabel(self.latmaxspl)
        self.latmax.setObjectName("latmax")
        self.latmaxline = QtWidgets.QLineEdit(self.latmaxspl)
        self.latmaxline.setObjectName("latmaxline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.latmin.setText(_translate("MainWindow", "Широта MIN"))
        self.lonmax.setText(_translate("MainWindow", "Долгота MAX"))
        self.lonmin.setText(_translate("MainWindow", "Долгота MIN"))
        self.btsearch.setText(_translate("MainWindow", "Поиск"))
        self.btclear.setText(_translate("MainWindow", "Очистить"))
        self.latmax.setText(_translate("MainWindow", "Широта MAX"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())